name: build projects

on:
  schedule:
    - cron: '0 3 * * *' # once a day at 3am
  push:
    branches:
      - master

jobs:
  collect_versions:
    name: Collect lean versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'

      - name: install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: retrieve version history
        run: curl https://raw.githubusercontent.com/leanprover-contrib/leanprover-contrib/store-version-history/version_history.yml --output version_history.yml

      - id: set-matrix
        run: |
          python test_builds.py load_versions versions.json
          echo "MATRIX=$(cat versions.json)" > $GITHUB_OUTPUT

  build_versions:
    name: Build for ${{matrix.version}}
    runs-on: ubuntu-latest
    needs: collect_versions
    if: toJson(fromJson(needs.collect_versions.outputs.matrix)) != '[]'
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.collect_versions.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'

      - name: install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: retrieve version history
        run: curl https://raw.githubusercontent.com/leanprover-contrib/leanprover-contrib/store-version-history/version_history.yml --output version_history.yml

      - name: build projects at ${{matrix.version}}
        run: |
          export OPENAI_API_KEY="${{ secrets.OPENAI_KEY }}" 
          python test_builds.py --version "${{matrix.version}}" --github_token "${{ secrets.LCB_TOKEN }}"
      
      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.version }}
          path: version_history.yml

  collate:
    name: Collate and deploy results
    runs-on: ubuntu-latest
    needs: build_versions
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'

      - name: install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect matrix outputs
        uses: actions/download-artifact@v3
        with:
          path: version_history

      - name: Retrieve version history
        run: curl https://raw.githubusercontent.com/leanprover-contrib/leanprover-contrib/store-version-history/version_history.yml --output version_history.yml

      - name: Merge files
        run: |
          shopt -s nullglob
          python test_builds.py concat_outputs version_history/*/*.yml
          cat version_history.yml

      - name: Write JS
        run: |
          python test_builds.py write_js
      
      - name: push version history
        run: |
          git config user.email "leanprover.community@gmail.com"
          git config user.name "leanprover-community-bot"
          git add -f version_history.yml projects.js
          git checkout --orphan master2
          git commit -m "auto update version history"
          git push -f origin HEAD:store-version-history
